### ISSUE TITLE
NaN outputs

### ISSUE THREAD

**Issue by james-oldfield** [kakaobrain/karlo#6]
Hi!

Thanks a lot for your work on this, it's great.

However, I'm having trouble running the `example.py` script. All I get are tensors full of `nan`s returned on line 66 of example.py. Did you see such an error before, and have an idea how I might be able to fix this?

Thanks!

**Comment by donghoonlee04** [comment]
It seems to work fine on my machine.
Could you share the seed, prompt, and log for reproduction?

**Comment by james-oldfield** [comment]
Hi, thanks for the fast reply!

I removed the checkpoints and re-downloaded them from scratch, and it seems this has fixed it (really no idea what happened there).

Thanks again for the helpful response. And great work!

James.
