### ISSUE TITLE
when i use the pipeline example, i got this error

### ISSUE THREAD

**Issue by Alfred-Duncan** [kakaobrain/karlo#7]
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, 
m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, 
ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by donghoonlee04** [comment]
Hi @Alfred-Duncan ,
I cannot reproduce the error. It seems to be related to CUDA installation, could you share your pytorch version and CUDA version ($ nvcc --version)?

**Comment by donghoonlee04** [comment]
You may try re-install them among these options
![image](https://user-images.githubusercontent.com/18273642/209277325-b2c968a3-afcb-4d39-8562-f9c4f7ed5afb.png)
or [previous versions](https://pytorch.org/get-started/previous-versions/)

**Comment by Alfred-Duncan** [comment]
@donghoonlee04 thank u for that, i already fix that problem, it's my version's fault
